executing on host: astro0001 with pid: 9157
tcgetattr: Inappropriate ioctl for device
[astro0001.rcf.bnl.gov:10556] [[1768,1],0] mca_oob_tcp_recv_handler: invalid message type: 2646389
[astro0001.rcf.bnl.gov:10554] [[1768,0],0] mca_oob_tcp_recv_handler: invalid message type: 2646389
[astro0001.rcf.bnl.gov:10556] [[1768,1],0] mca_oob_tcp_recv_handler: recv() failed: Connection reset by peer (104)
[astro0001.rcf.bnl.gov:10554] [[1768,0],0] mca_oob_tcp_recv_handler: recv() failed: Connection reset by peer (104)
[astro0002.rcf.bnl.gov:06389] [[1768,1],1] mca_oob_tcp_recv_handler: invalid message type: 2646389
[astro0002.rcf.bnl.gov:06389] [[1768,1],1] mca_oob_tcp_recv_handler: recv() failed: Connection reset by peer (104)
Connection to astro0001 closed.
caught exception type: <class 'socket.error'>  details: [Errno 111] Connection refused
mpirun -np 2 -npernode 1 -hostfile %hostfile% ./RunJob.py

Traceback (most recent call last):
  File "/astro/u/astrodat/local/bin/wq", line 1012, in <module>
    main()
  File "/astro/u/astrodat/local/bin/wq", line 989, in main
    cmd_obj.execute()
  File "/astro/u/astrodat/local/bin/wq", line 833, in execute
    sres = send_message(self.message)
  File "/astro/u/astrodat/local/bin/wq", line 868, in send_message
    socket_connect(sock, conninfo, crash_on_timeout=crash_on_timeout)
  File "/astro/u/astrodat/local/bin/wq", line 853, in socket_connect
    sock.connect(conninfo)
  File "/opt/astro/SL64/anaconda/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
